### ISSUE TITLE
creation of API tests in robotframeworks

### ISSUE THREAD

**Issue by BPylypenko** [odahu/odahu-flow#247]
Decided to create them through odahu sdk.
'Cause it's ease maintenance and writing of tests for API with (if have) impact on 

- [x] create sdk wrapper to smoothly connect sdk with robotframeworks.
- [x] write positive tests for API through SDK
- [x] write negative tests for API through SDK
