### ISSUE TITLE
[EPIC] 3rd party services versions tracking list for updates

### ISSUE THREAD

**Issue by alinaignatiuk** [odahu/odahu-flow#608]
Check list of tasks in the issues description

**Comment by alinaignatiuk** [comment]
- [ ] Create checklist of up to date 3rd party services embedded in ODAHU (start from ODAHU 3rd services tab and expand it) on [EPAM kb page](https://kb.epam.com/display/EPMCBDCC/%5BODAHU%5D+ODAHU+3rd+party+service+update)
- [ ] Add current version and latest available version for each service in the list; 
- [ ] Assign priority for the services versions update;

**Comment by karbyshevd** [comment]
Checklist is created, versions added.
