### ISSUE TITLE
[EPIC] Improvements in ODAHU development process

### ISSUE THREAD

**Issue by alinaignatiuk** [odahu/odahu-flow#609]
Check list of tasks in the issues description

**Comment by alinaignatiuk** [comment]
- [ ] Deployment checklist ( please [review on kb](https://kb.epam.com/display/EPMCBDCC/%5BODAHU%5D+Deployment+checklist), update if required, check whether there are any differences/dependencies on deployment env?)  - @karbyshevds 
- [ ] Create Release check list. Please [add to the kb](https://kb.epam.com/display/EPMCBDCC/%5BODAHU%5D+Release+checklist) @karbyshevds 
- [x] Create Ongoing and release tests check list. Please [add to the kb](https://kb.epam.com/display/EPMCBDCC/%5BODAHU%5D+Tests+Check+list) @BPylypenko 
- [x] Review of the ODAHU services inputs, description of outputs. Review & update quick start guide. @alinaignatiuk  review with @lev-titov 
- [ ] Automation opportunities in ODAHU testing. Check if any exist - @BPylypenko 
- [ ] Automation opportunities in ODAHU CI/CD - @karbyshevds 
- [ ] Create Code review checklist. Please [add to the kb](https://kb.epam.com/display/EPMCBDCC/%5BODAHU%5D+Code+review+checklist)
- [ ] How can we automate ODAHU release updates without downtime?
